<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AspireUseCliBundle>true</AspireUseCliBundle>
        <UserSecretsId>9329437c-899a-479b-bff3-7c0298f7d3eb</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Catalog.Api\Catalog.Api.csproj" />
      <ProjectReference Include="..\..\Basket.Api\Basket.Api.csproj" />
      <ProjectReference Include="..\..\Gateway\Gateway.csproj" />
      <ProjectReference Include="..\..\Order.Api\Order.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="13.6.0" />
      <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.5.4-preview.1.26464.4" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.4" />
      <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.6.0" />
      <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.4" />
    </ItemGroup>

    <ItemGroup>
      <None Update="KeycloakConfig\realm-export.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
